name: multirtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  # For running
  - python>=3.9,<3.10
  - pip
  # OPERA RTC-sourced requirements
  - gdal>=3.0
  - numpy>=1.20
  - boto3
  - shapely
  - s1reader>=0.2.4
  - isce3==0.15.0
  - sarpy
  - earthaccess
  - burst2safe
  # Workaround for the issue with `libabseil` (09/11/2023)
  - libabseil=20230125.3
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - ruff
