name: multirtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  # For running
  - python
  - pip
  # OPERA RTC-sourced requirements
  - gdal>=3.0
  - numpy>=1.20
  - boto3
  - shapely
  - s1reader>=0.2.4
  - isce3
  - sarpy
  - earthaccess
  - burst2safe
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - ruff
