name: multirtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  # ISCE3
  - cmake
  - cxx-compiler
  - eigen
  - fftw
  - gdal
  - emacs
  - gmock
  - gtest
  - gcc_linux-64 < 10
  - gxx_linux-64 < 10
  - gfortran_linux-64
  - gfortran
  - h5py
  - hdf5!=1.14.2
  - libgcc-ng
  - libstdcxx-ng
  - numpy<1.26.0
  - pybind11
  - pyre
  - pytest
  - cython
  - ruamel.yaml
  - scipy=1.9
  - shapely
  - yamale
  - backoff
  - pyaps3
  - xarray
  - pysolid
  - matplotlib
  - scipy
  - libgdal-hdf5
  - libnetcdf
  # MultiRTC
  - burst2safe
  - matplotlib
  - pandas
  - lmfit
  - scikit-image
  - hyp3lib
  - sarpy
  - netcdf4
  - patsy
  - cftime
  - statsmodels
  - boto3
  - requests
  - lxml
  - tqdm
  - ruamel.yaml
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - ruff
