[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "multirtc"
requires-python = ">=3.10"
authors = [
    {name="Forrest Williams", email="ffwilliams2@alaska.edu"},
]
description = "Python library for multi-sensor RTC processing using the OPERA algorithm"
license = {text = "BSD-3-Clause"}
classifiers=[
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "gdal",
    "numpy",
    # "isce3", Not on pip
    "boto3",
    "requests",
    "lxml",
    "shapely",
    "pyproj",
    "sarpy",
    "burst2safe",
    "tqdm",
    "urllib3",
    "matplotlib",
    "pandas",
    "lmfit",
    "scipy",
    "scikit-image",
]
dynamic = ["version", "readme"]

[project.optional-dependencies]
develop = ["pytest", "pytest-cov", "pytest-console-scripts", "ruff"]

[project.urls]
Homepage = "https://github.com/forrestfwilliams/multirtc"
Documentation = "https://github.com/forrestfwilliams/multirtc"

[project.scripts]
multirtc = "multirtc.__main__:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
script_launch_mode = "subprocess"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]

[tool.ruff]
line-length = 120
# The directories to consider when resolving first- vs. third-party imports.
# See: https://docs.astral.sh/ruff/settings/#src
src = ["src", "tests"]

[tool.ruff.format]
indent-style = "space"
quote-style = "single"

[tool.ruff.lint]
extend-select = [
    "I",   # isort: https://docs.astral.sh/ruff/rules/#isort-i
    "UP",  # pyupgrade: https://docs.astral.sh/ruff/rules/#pyupgrade-up
    # TODO: Uncomment the following extensions and address their warnings:
    # "D",   # pydocstyle: https://docs.astral.sh/ruff/rules/#pydocstyle-d
    # "ANN", # annotations: https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
    # "PTH", # use-pathlib-pth: https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
case-sensitive = true
lines-after-imports = 2

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[tool.pixi.pypi-options]
no-build-isolation = ['isce3']

[tool.pixi.dependencies]
pip = "*"
gdal = ">=3.0"
libgdal-netcdf = "*"
numpy = ">=1.20"
boto3 = "*"
h5netcdf = "*"
hdf5 = "*"
cxx-compiler = "*"
pkgconfig = "*"
fftw = "*"
pybind11 = "*"
requests = "*"
lxml = "*"
shapely = "*"
pyproj = "*"
pysolid = "*"
backoff = "*"
ruamel = "*"
yamale = "*"
sarpy = "*"
burst2safe = "*"
tqdm = "*"
urllib3 = "*"
matplotlib = "*"
pandas = "*"
lmfit = "*"
scipy = "*"
scikit-image = "*"
setuptools = "*"
setuptools_scm = "*"
wheel = "*"
pytest = "*"
pytest-console-scripts = "*"
pytest-cov = "*"
ruff = "*"

[tool.pixi.target.linux-64.dependencies]
pyre = "*"

[tool.pixi.target.linux-aarch64.pypi-dependencies]
pyre = "*"

[tool.pixi.target.osx-64.dependencies]
pyre = "*"

[tool.pixi.target.osx-arm64.dependencies]
pyre = "*"

[tool.pixi.feature.pycharm.dependencies]
pixi-pycharm = "*"

[tool.pixi.feature.py310.dependencies]
python = "3.10.*"

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.environments]
default = { features = ["develop", "pycharm"], solve-group = "default" }
py310 = { features = ["develop", "py310"]}
py311 = { features = ["develop", "py311"]}
py312 = { features = ["develop", "py312"], solve-group = "default"}

[tool.pixi.tasks.install-isce3]
cmd = [
    "python",
    "-m",
    "pip",
    "install",
    "h5py",
    "git+https://github.com/isce-framework/isce3.git",
]
depends-on = []

[tool.pixi.tasks.install-radar]
cmd = [
    "python",
    "-m",
    "pip",
    "install",
    "ruamel.yaml",
    "git+https://github.com/opera-adt/COMPASS.git",
    "git+https://github.com/isce-framework/s1-reader.git",
]
depends-on = ["install-isce3"]

[tool.pixi.tasks.install-editable]
cmd = [
    "python",
    "-m",
    "pip",
    "install",
    "-e",
    ".",
]
depends-on = ["install-radar"]

[tool.pixi.tasks.tests]
cmd = [
    "pytest",
    "--cov=multirtc",
]
depends-on = ["install-editable"]
